// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDngNFZr3a0L4hR8p9wB0TJJBL12nM0g-U',
    appId: '1:563451378875:web:aad7e185149fb0d4943d9e',
    messagingSenderId: '563451378875',
    projectId: 'parametre-cf052',
    authDomain: 'parametre-cf052.firebaseapp.com',
    storageBucket: 'parametre-cf052.firebasestorage.app',
    measurementId: 'G-19ZB3T1ZP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCYeCkvLI-HvlQhpIX2zwcZALDS89MFoU',
    appId: '1:563451378875:android:cf362daeffc4b64f943d9e',
    messagingSenderId: '563451378875',
    projectId: 'parametre-cf052',
    storageBucket: 'parametre-cf052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUOp3r5o175KU7m_0IQEFXOeajbYPl88',
    appId: '1:563451378875:ios:aed78f39a391a2fc943d9e',
    messagingSenderId: '563451378875',
    projectId: 'parametre-cf052',
    storageBucket: 'parametre-cf052.firebasestorage.app',
    iosClientId: '563451378875-19j440i4stsu5c46sufu8r0cqulkfgsp.apps.googleusercontent.com',
    iosBundleId: 'com.kisisel.asistan.kisiselAsistan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNUOp3r5o175KU7m_0IQEFXOeajbYPl88',
    appId: '1:563451378875:ios:aed78f39a391a2fc943d9e',
    messagingSenderId: '563451378875',
    projectId: 'parametre-cf052',
    storageBucket: 'parametre-cf052.firebasestorage.app',
    iosClientId: '563451378875-19j440i4stsu5c46sufu8r0cqulkfgsp.apps.googleusercontent.com',
    iosBundleId: 'com.kisisel.asistan.kisiselAsistan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDngNFZr3a0L4hR8p9wB0TJJBL12nM0g-U',
    appId: '1:563451378875:web:896b62cef7c6321d943d9e',
    messagingSenderId: '563451378875',
    projectId: 'parametre-cf052',
    authDomain: 'parametre-cf052.firebaseapp.com',
    storageBucket: 'parametre-cf052.firebasestorage.app',
    measurementId: 'G-P387LYQ0DN',
  );
}
