# Set platform to iOS 14.0 as required by the health plugin
platform :ios, '14.0'

# CocoaPods analytics sends network stats so disable it.
install! 'cocoapods', :deterministic_uuids => false

# Flutter User-Defined Variables
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Force the deployment target of all pods to 14.0 to match the main target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
